root: ../data/exp/point2d
seed_offset: 0

num_instances: 1
save_instance_images: false
instance:
  _target_: MRMP.gen_random_instance_StatePoint2D
  N_min: 2
  N_max: 8
  rad_min: 0.025
  rad_max: 0.1
  num_obs_min: 0
  num_obs_max: 10
  rad_obs_min: 0.05
  rad_obs_max: 0.10

solvers_common: &solvers_common
  num_vertices: 30
  max_makespan: 20
  TIME_LIMIT: 30
  # roadmaps_growing_rate: 2.0

solvers:
  - _target_: MRMP.prioritized_planning
    <<: *solvers_common
  - _target_: MRMP.conflict_based_search
    collision_weight: 0.0
    <<: *solvers_common
  - _target_: MRMP.conflict_based_search
    collision_weight: 0.5
    <<: *solvers_common
  - _target_: MRMP.conflict_based_search
    collision_weight: 1.0
    <<: *solvers_common
  - _target_: MRMP.conflict_based_search
    collision_weight: 1.5
    <<: *solvers_common
