root: ../data/exp/arm22
seed_offset: 0

num_instances: 1000
save_instance_images: false
save_animation: false
anim_plot_params:
  interpolate_depth: 2
  fps: 3

instance:
  _target_: MRMP.gen_random_instance_StateArm22
  N_min: 2
  N_max: 6
  rad_min: 0.15
  rad_max: 0.25
  num_obs_min: 0
  num_obs_max: 3
  rad_obs_min: 0.05
  rad_obs_max: 0.10

solvers:
  - _target_: MRMP.RRT
    steering_depth: 2
    epsilon: 0.5
  - _target_: MRMP.PP
    num_vertices: 100
    max_makespan: 20
    rad: 0.3
    roadmaps_growing_rate: 2.0
  - _target_: MRMP.PRM_direct
    epsilon: 4.0
  - _target_: MRMP.RRT_connect
    steering_depth: 2
    epsilon: 0.2
  - _target_: MRMP.CBS
    num_vertices: 100
    max_makespan: 10
    rad: 0.3
    roadmaps_growing_rate: 1.5
    collision_weight: 4.0
