root: ../data/exp/arm33
seed_offset: 0

num_instances: 1000
save_instance_images: false
save_animation: false
anim_plot_params:
  interpolate_depth: 2
  fps: 3

instance:
  _target_: MRMP.gen_random_instance_StateArm33
  N_min: 2
  N_max: 8
  rad_min: 0.15
  rad_max: 0.25
  num_obs_min: 0
  num_obs_max: 4
  rad_obs_min: 0.1
  rad_obs_max: 0.15

solvers:
  # - _target_: MRMP.planner1
  # - _target_: MRMP.RRT_connect
  - _target_: MRMP.PP
