root: ../data/exp/dubins2d
seed_offset: 0

num_instances: 1000

save_instance_images: false
save_animation: false
anim_plot_params:
  interpolate_depth: 2
  fps: 3

instance:
  _target_: MRMP.gen_random_instance_StateDubins
  N_min: 2
  N_max: 8
  rad_min: 0.025
  rad_max: 0.075
  num_obs_min: 0
  num_obs_max: 8
  rad_obs_min: 0.05
  rad_obs_max: 0.07

solvers:
  - _target_: MRMP.RRT
    steering_depth: 1
    epsilon: 2.0
  - _target_: MRMP.PP
    num_vertices: 50
    max_makespan: 20
    rad: 0.5
    roadmaps_growing_rate: 2.0
  - _target_: MRMP.PRM_direct
    epsilon: 1.0
  - _target_: MRMP.RRT_connect
    steering_depth: 2
    epsilon: ~
  - _target_: MRMP.CBS
    num_vertices: 100
    max_makespan: 20
    rad: 0.5
    roadmaps_growing_rate: ~
    collision_weight: 0.5
