root: ../data/exp/line2d
seed_offset: 0

num_instances: 1000
save_instance_images: false
save_animation: false
anim_plot_params:
  interpolate_depth: 2
  fps: 3

instance:
  _target_: MRMP.gen_random_instance_StateLine2D
  N_min: 2
  N_max: 8
  rad_min: 0.05
  rad_max: 0.15
  num_obs_min: 0
  num_obs_max: 8
  rad_obs_min: 0.05
  rad_obs_max: 0.10

solvers:
  - _target_: MRMP.PP
    num_vertices: 70
    max_makespan: 10
    rad: 0.3
    roadmaps_growing_rate: 1.1
