root: ../data/exp/point3d
seed_offset: 0

num_instances: 1000
save_instance_images: false
save_animation: false
anim_plot_params:
  interpolate_depth: 2
  fps: 3

instance:
  _target_: MRMP.gen_random_instance_StatePoint3D
  N_min: 2
  N_max: 8
  rad_min: 0.1
  rad_max: 0.15
  num_obs_min: 0
  num_obs_max: 10
  rad_obs_min: 0.1
  rad_obs_max: 0.15

solvers:
  - _target_: MRMP.RRT
    steering_depth: 2
    epsilon: 2.0
  - _target_: MRMP.PP
    num_vertices: 200
    max_makespan: 20
    rad: 0.3
    roadmaps_growing_rate: 1.0
  - _target_: MRMP.PRM_direct
    epsilon: 0.5
  - _target_: MRMP.RRT_connect
    steering_depth: 4
    epsilon: 0.2
  - _target_: MRMP.CBS
    num_vertices: 200
    max_makespan: 20
    rad: 0.3
    roadmaps_growing_rate: 1.5
    collision_weight: 1.0
  - _target_: MRMP.planner3
    init_min_dist_thread: 0.2
    decreasing_rate_min_dist_thread: 0.99
    steering_depth: 2
    epsilon: 0.5
    num_vertex_expansion: 30
    # for fairness
    no_fast_collision_check: true
