root: ../data/exp/point3d
seed_offset: 0

num_instances: 100
save_instance_images: false
instance:
  _target_: MRMP.gen_random_instance_StatePoint3D
  N_min: 2
  N_max: 8
  rad_min: 0.1
  rad_max: 0.15
  num_obs_min: 0
  num_obs_max: 10
  rad_obs_min: 0.1
  rad_obs_max: 0.15

solvers_common: &solvers_common
  TIME_LIMIT: 30

solvers:
  - _target_: MRMP.prioritized_planning
    <<: *solvers_common
    num_vertices: 70
    rad: 0.3
    roadmaps_growing_rate: 1.1
    max_makespan: 10

  - _target_: MRMP.conflict_based_search
    <<: *solvers_common
    collision_weight: 1.0
    num_vertices: 90
    roadmaps_growing_rate: null
    max_makespan: 10

  - _target_: MRMP.Solvers.planner1
    <<: *solvers_common
    num_vertex_expansion: 10
    init_min_dist_thread: 0.1
    decreasing_rate_min_dist_thread: 0.99
