root: ../data/exp/hypra_line2d
seed_offset: 10000
num_instances: 50
num_search_times: 500
time_limit: 10

instance: ./scripts/config/eval/line2d.yaml

solvers_common: &solvers_common
  num_vertices:
    - 30
    - 50
    - 70
    - 90
  rad:
    - null
    - 0.05
    - 0.1
    - 0.3
    - 0.5
  max_makespan:
    - 10
    - 20
  roadmaps_growing_rate:
    - null
    - 1.0
    - 1.1
    - 1.5
    - 2.0

solvers:
  - _target_: MRMP.prioritized_planning
    <<: *solvers_common
  - _target_: MRMP.conflict_based_search
    <<: *solvers_common
    collision_weight:
      - 0.0
      - 0.1
      - 0.5
      - 1.0
