root: ../data/exp/hypra
seed_offset: 10000
num_instances: 50
num_search_times: 100
time_limit: 30

solvers_common_params_mapf: &solvers_common_params_mapf
  num_vertices:
    - 50
    - 100
    - 200
    - 400
  rad:
    - null
    - 0.1
    - 0.3
    - 0.5
    - 1.0
    - 2.0
  max_makespan:
    - 10
    - 20
  roadmaps_growing_rate:
    - null
    - 1.0
    - 1.5
    - 2.0

solvers_common_params_rrt: &solvers_common_params_rrt
  steering_depth:
    - 0
    - 1
    - 2
    - 4
  epsilon:
    - null
    - 0.1
    - 0.2
    - 0.5
    - 1.0
    - 2.0
    - 4.0

solvers:
  - _target_: MRMP.PP
    <<: *solvers_common_params_mapf
  - _target_: MRMP.CBS
    <<: *solvers_common_params_mapf
    collision_weight:
      - 0.0
      - 0.5
      - 1.0
      - 2.0
      - 4.0
  - _target_: MRMP.RRT
    <<: *solvers_common_params_rrt
  - _target_: MRMP.RRT_connect
    <<: *solvers_common_params_rrt
  - _target_: MRMP.PRM_direct
    epsilon:
      - null
      - 0.1
      - 0.2
      - 0.5
      - 1.0
      - 2.0
      - 4.0
  - _target_: MRMP.planner3
      - 1
      - 2
      - 4
    epsilon:
      - null
      - 0.1
      - 0.2
      - 0.5
      - 1.0
      - 2.0
      - 4.0
    num_vertex_expansion:
      - 5
      - 10
      - 15
      - 20
      - 30
    init_min_dist_thread:
      - 0.01
      - 0.05
      - 0.1
      - 0.2
      - 0.4
    decreasing_rate_min_dist_thread:
      - 0.99
      - 0.5
