seed_start: 1
num_instances: 100

generator:
  target: MRMP.gen_random_instance_StateCapsule3D
  params:
    N_min: 2
    N_max: 8
    rad_min: 0.05
    rad_max: 0.15
    num_obs_min: 0
    num_obs_max: 10
    rad_obs_min: 0.1
    rad_obs_max: 0.15
