seed_start: 1
num_instances: 100

generator:
  target: MRMP.gen_random_instance_StatePoint3D
  params:
    N_min: 4
    N_max: 10
    rad_min: 0.1
    rad_max: 0.2
    num_obs_min: 0
    num_obs_max: 10
    rad_obs_min: 0.1
    rad_obs_max: 0.15
