seed_start: 1
num_instances: 100

generator:
  target: MRMP.gen_random_instance_StatePoint2D
  params:
    N: 50
    rad_min: 0.02
    rad_max: 0.04
    num_obs: 10
    rad_obs_min: 0.02
    rad_obs_max: 0.08
