benchmark_file: ../data/benchmark/ijcai23/main/capsule3d.jld2

seed_start: 1
seed_end: 10
time_limit_sec: 300

postprocessing:
  - target: send_slack_msg
    params:
      msg: "done: main/capsule3d"

solvers:
  - target: "MRMP.CBS"
    params:
      num_vertices: 200
      max_makespan: 10
      rad: 1.0
      roadmaps_growing_rate: 1.5
      collision_weight: 2.0
  - target: "MRMP.PP"
    params:
      num_vertices: 400
      max_makespan: 10
      rad: ~
      roadmaps_growing_rate: 2.0
  - target: "MRMP.PRM_direct"
    params:
      epsilon: 4.0
  - target: "MRMP.RRT"
    params:
      steering_depth: 1
      epsilon: ~
  - target: "MRMP.RRT_connect"
    params:
      steering_depth: 2
      epsilon: 4.0
  - target: "MRMP.SSSP"
    params:
      init_min_dist_thread: 0.4
      decreasing_rate_min_dist_thread: 0.5
      steering_depth: 1
      epsilon: ~
      num_vertex_expansion: 10
