benchmark_file: ../data/benchmark/ijcai23/main/point2d.jld2

seed_start: 1
seed_end: 1
time_limit_sec: 10

postprocessing:
  - target: send_slack_msg
    params:
      msg: "done: main/point2d"

solvers:
  - target: MRMP.SSSP
    params:
      init_min_dist_thread: 0.1
      decreasing_rate_min_dist_thread: 0.5
      steering_depth: 4
      epsilon: 4.0
      num_vertex_expansion: 10
